### ISSUE TITLE
Documentation on the CAPIBehaviour and CouchbaseBehaviour interface.

### ISSUE THREAD

**Issue by zooldk** [couchbaselabs/couchbase-capi-server#1]
Right now it is quite hard to know what to implement when you are implementing the two interfaces.

A documentation on these would be great.

**Comment by dnault** [comment]
Thank you for bringing this to our attention (and apologies for the belated response).

The couchbase-capi-server project is no longer maintained. In preparation for archiving this repository, all issues are being closed as "won't fix".
