### ISSUE TITLE
Add to Central Maven Repository?

### ISSUE THREAD

**Issue by mattjmcelroy** [couchbaselabs/couchbase-capi-server#2]
This project is great!  Is there any possibility we can add this to the Maven central repository?  I noticed if you want to build the Couchbase Transport Plugin for Elastic Search (https://github.com/couchbaselabs/elasticsearch-transport-couchbase), you have to build this to your local repository first.

**Comment by dnault** [comment]
Thank you for bringing this to our attention (and apologies for the belated response).

The couchbase-capi-server project is no longer maintained. In preparation for archiving this repository, all issues are being closed as "won't fix".
