### ISSUE TITLE
Version tags

### ISSUE THREAD

**Issue by mattjmcelroy** [couchbaselabs/couchbase-capi-server#3]
I noticed there are some interface changes between version 1.2.0 and 1.3.0, and specific version of this project are required for compatibility with specific Elastic Search Couchbase Plugin versions (and specific Couchbase versions).  It would be very helpful to have tags on each release.  Currently, if someone wants to build, for example, version 1.2.0, they have to find the version-related comment and checkout based on commit b6d9c9ec71e81a376ff28130d93bc2463132d8ae, then build.

**Comment by dnault** [comment]
Thank you for bringing this to our attention (and apologies for the belated response).

The couchbase-capi-server project is no longer maintained. In preparation for archiving this repository, all issues are being closed as "won't fix".
