### ISSUE TITLE
POM.xml source/target define Java 7, Jetty upgrade requires Java 8+

### ISSUE THREAD

**Issue by pdeaudney** [couchbaselabs/couchbase-capi-server#7]
In https://github.com/couchbaselabs/couchbase-capi-server/pull/6/commits/d7623487013dd77b7da33f2a8adb3de5e189b459 the jetty version defined requires Java 8 as per http://www.eclipse.org/jetty/download.html

Using Jetty `9.2.17.v20160517` may be more suitable given that the POM.xml still has the source/target versions of Java defined as 1.7.

**Comment by dnault** [comment]
Thank you for bringing this to our attention (and apologies for the belated response).

The couchbase-capi-server project is no longer maintained. In preparation for archiving this repository, all issues are being closed as "won't fix".
