### ISSUE TITLE
Update Jackson-mapper-asl to jackson-databind

### ISSUE THREAD

**Issue by CJMNgo** [couchbaselabs/couchbase-capi-server#8]
The version of Jackson-mapper-asl is EOL.  The project has moved to https://github.com/FasterXML/jackson-databind and they are on version 2.8.5.  Locally, I was able to get couchbase-capi-server to build by making changes to the include statements to use the new namespace.

**Comment by dnault** [comment]
Thank you for bringing this to our attention (and apologies for the belated response).

The couchbase-capi-server project is no longer maintained. In preparation for archiving this repository, all issues are being closed as "won't fix".
